### PR TITLE
remove auto-generated mocks from source

### PR DESCRIPTION
**Pull request by sanju50201**
**What type of PR is this?**

**Which issue does this PR fix**:
#322 

**What does this PR do / Why do we need it**:
Removed the mock generated files

**If an issue # is not available please add repro steps and logs from aws-gateway-controller showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this PR introduce any new dependencies?**:

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mikhail-aws** [comment]
thanks for PR, 

> We need to remove generated mock files

We need to remove not "mock generators" but files that produced by generator, for example vpclattice.go generates vpclattice_mocks.go.

Everything that can be auto-generated should not be part of source code. So we need to remove files that has *_mock.go in it. These files can be always reproduced by running ./scripts/gen_mocks.sh or `go generate ./...`

**Comment by sanju50201** [comment]
> thanks for PR,
> 
> > We need to remove generated mock files
> 
> We need to remove not "mock generators" but files that produced by generator, for example vpclattice.go generates vpclattice_mocks.go.
> 
> Everything that can be auto-generated should not be part of source code. So we need to remove files that has *_mock.go in it. These files can be always reproduced by running ./scripts/gen_mocks.sh and `go generate ./...`

okay, will work on it

**Comment by mikhail-aws** [comment]
still working on it?

**Comment by mikhail-aws** [comment]
closing due to inactivity

**Pull request closed without merging**
