### PR TITLE
fix: issue #310 remove config global vars

### PR DESCRIPTION
**Pull request by rmullinnix461332**
**What type of PR is this?**
cleanup

**Which issue does this PR fix**:
#310 

**What does this PR do / Why do we need it**:
removes global vars.  adds getters and a few setter functions to retrieve var values.

**If an issue # is not available please add repro steps and logs from aws-gateway-controller showing the issue**:

**Testing done on this change**:

existing tes cases
**Automation added to e2e**:

no, no functional change
**Will this PR introduce any new dependencies?**:

no
**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:
no
**Does this PR introduce any user-facing change?**:

no
```release-note
Removed global config vars and replaced with GetXXX() functions that read env vars.  Set function for VPC only called from test case.
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mikhail-aws** [comment]
The original problem is that we stick values to the package globals. Wrapping globals into getter's and setter's does not address underlying issue. I do like wrapping each variable into own function, looks neat.

To address globals issue we need:
- create a struct that will hold configurations, not package variables
- initialize struct in main.go
- propagate config through constructors or context to the places where we need then

**Review by rmullinnix461332 — COMMENTED** [review]
the main issue I see with this is the amount of calls that originate from _test.go modules.  The init() in main() doesn't cover the test runs.  You end up having to InitConfig() in every test function or add a TestMain().  Would it be ok to have a separate test config that is like what I coded - just reading from env vars.  Then the controller_config for main() and use in packages.  Trying to pass the config struct through context in test cases, especially the mock client was problematic.

**Comment by mikhail-aws** [comment]
>  You end up having to InitConfig() in every test function or add a TestMain()

There are other options. For example you can create a config struct in controller_config.go
```go
type Config struct {
	VpcId                 string
	AccountId             string
	Region                string
	LogLevel              string
	DefaultServiceNetwork string
	UserLongTGName        bool
}
```

in tests for a package create an instance of config - global package variable for tests. For example pkg/deploy/lattice/config_test.go
```go
var testConfig = Config { ... populate with fields ... }
```

And then in current test file we only need to replace "config.VpcId" with "testConfig.VpcId". Which is basic find/replace.
```go
latticeDataStore.AddServiceNetwork(tt.meshName, config.AccountID, tt.meshArn, tt.meshId, latticestore.DATASTORE_SERVICE_NETWORK_CREATED)

// will become

latticeDataStore.AddServiceNetwork(tt.meshName, testConfig.AccountID, tt.meshArn, tt.meshId, latticestore.DATASTORE_SERVICE_NETWORK_CREATED)
```

this helps with 2 things:
1. decouple variables from package into struct, with minimal changes in current code
2. makes it easier to propagate config in future refactoring

**Review by mikhail-aws — CHANGES_REQUESTED** [review]
It's very large diff. Considering lots of changes currently happening it's pretty hard to do it in one shot. I still recommend to cut down a scope and do little changes starting from controller_config.go wrapping configs into a struct. A start config propagation little by little. It's more than 1 PR.

**Comment by mikhail-aws** [comment]
closing due to inactivity, also some of configuration changes already merged into cloud.go

**Pull request closed without merging**
